# Generated by Django 5.0.8 on 2025-09-06 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_alter_useremployee_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 6, 20, 20, 51, 996836)),
        ),
    ]
