# Generated by Django 5.0.8 on 2025-09-08 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_alter_useremployee_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 4, 50, 49, 564994)),
        ),
    ]
