# Generated by Django 5.0.8 on 2025-09-08 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_usermanage_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 8, 4, 50, 49, 533686)),
        ),
    ]
