# Generated by Django 5.0.8 on 2025-09-08 03:34

import django.db.models.deletion
import django_resized.forms
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduler', '0015_alter_profilemoduler_modulerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatgoryProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulercatgoryitems', to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('moduler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('emp_name', models.CharField(max_length=150)),
                ('close_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closeempitems', to='shop.closedday')),
                ('moduler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('type_order', models.CharField(max_length=130)),
                ('is_finished', models.BooleanField(default=False)),
                ('stay', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Payment', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Payment_order', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('barcode', models.ImageField(blank=True, default='profile_pictures/barcode.png', upload_to='images/')),
                ('barcode_id', models.CharField(max_length=13, null=True)),
                ('close_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.closedday')),
                ('close_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closeordersitems', to='shop.closedemp')),
                ('moduler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderuser', to=settings.AUTH_USER_MODEL)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordermanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('price_sale', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity_box', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('type_quantity', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(default='qta3e', max_length=100, null=True)),
                ('product_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to=shop.models.upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_id', models.IntegerField(default=1)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('barcode_id', models.CharField(max_length=13, null=True)),
                ('total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsmoduler', to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productmanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceBuyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productitems', to='shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('img', models.CharField(default='', max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_quantity', models.CharField(max_length=100, null=True)),
                ('dec_product', models.TextField()),
                ('is_finished', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='shop.products')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderBackDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('img', models.CharField(default='', max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_quantity', models.CharField(max_length=100, null=True)),
                ('dec_product', models.TextField()),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderbackitems', to='shop.order')),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderbackmanager', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderbackproductitems', to='shop.products')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(through='shop.OrderDetails', to='shop.products'),
        ),
    ]
