# Generated by Django 5.0.8 on 2025-09-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
