# Generated by Django 5.0.8 on 2025-09-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_products_total_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricebuyproduct',
            name='total_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
