# Generated by Django 5.0.8 on 2025-09-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togar', '0002_tagerdof3atmodel_tagerinvoicmodel_tagerinvoicdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagerinvoicmodel',
            name='stay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
