# Generated by Django 5.0.8 on 2025-09-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togar', '0003_alter_tagerinvoicmodel_stay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagerinvoicmodel',
            name='Payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tagerinvoicmodel',
            name='stay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tagerinvoicmodel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
