# Generated by Django 5.0.8 on 2025-09-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togar', '0004_alter_tagerinvoicmodel_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagerdof3atmodel',
            name='dof3a',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tagerinvoicdetails',
            name='price_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tagerinvoicdetails',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
